import LegalPage, { PolicySections } from "@/components/LegalPage";
import { createSeoMetadata } from "@/lib/data";

export const metadata = createSeoMetadata("terms", "/terms-conditions");

const sections = [
  { heading: "1. Introduction & Acceptance", paragraphs: ["These Terms & Conditions govern access to and use of the websites, software products, applications, APIs, technology platforms, cloud and infrastructure services, implementation services, technical support, Microsoft and IT solutions, and other technology services provided by Kashless Ventures Private Limited.", "By accessing or using the applicable Services, you agree to these Terms. Where a separate written agreement, Statement of Work, purchase order, Master Services Agreement, or other commercial agreement applies, that agreement governs the relevant Services to the extent of any conflict."] },
  { heading: "2. Eligibility & Authority", paragraphs: ["You must have the legal capacity to enter into a binding agreement and provide accurate information where registration or onboarding is required. If you act for an entity, you represent that you are authorized to bind it."] },
  { heading: "3. Services & Scope", paragraphs: ["Kashless Ventures provides technology solutions and related business services, including custom software, product engineering, FinTech and digital-lending technology, APIs, integration, workflow automation, cloud, infrastructure, DevOps, Microsoft products and licensing, hardware, IT infrastructure, business consultation, and strategic partnership support where separately agreed. The applicable written agreement governs scope, deliverables, timelines, dependencies, service levels, and fees."] },
  { heading: "4. Technology Provider; No Financial Services Representation", paragraphs: ["Kashless Ventures provides technology and software solutions. Unless expressly stated in a separate written agreement and legally permitted, it does not represent itself as a bank, NBFC, lender, payment system operator, credit bureau, or other regulated financial institution merely by providing technology Services.", "Third-party payment, banking, KYC, verification, credit, lending, cloud, messaging, and other services remain subject to their providers' terms, availability, policies, and regulatory requirements."] },
  { heading: "5. Microsoft, Hardware & Third-Party Products", paragraphs: ["Availability, pricing, licensing rights, renewals, warranties, support, and usage restrictions for Microsoft products, subscriptions, cloud solutions, security products, hardware, and other third-party technology products are subject to the applicable commercial arrangement and provider terms."] },
  { heading: "6. Accounts, Access & Credentials", paragraphs: ["You are responsible for maintaining the confidentiality of account credentials, API keys, passwords, and access tokens, and must promptly notify Kashless Ventures of suspected unauthorized access or security incidents."] },
  { heading: "7. Acceptable Use & Client Responsibilities", paragraphs: ["You must use the Services lawfully and in accordance with applicable agreements. Do not attempt unauthorized access, introduce malware, misuse integrations, facilitate unlawful activity, or reverse-engineer proprietary software except where permitted by law. You are responsible for accurate requirements, approvals, access, credentials, data, and dependencies needed for delivery."] },
  { heading: "8. Development, Delivery & Dependencies", paragraphs: ["Delivery timelines may depend on client-provided infrastructure, domains, credentials, APIs, third-party services, approvals, cloud accounts, data, and other dependencies. Milestones, acceptance criteria, and deliverables are defined in the applicable commercial agreement."] },
  { heading: "9. Third-Party Services & Integrations", paragraphs: ["Kashless Ventures is not responsible for outages, policy or pricing changes, API changes, suspension, rejection, latency, or other failures originating solely from third-party providers."] },
  { heading: "10. Fees, Taxes & Payment", paragraphs: ["Fees, milestones, commercial conditions, applicable taxes, and third-party costs are specified in the applicable proposal, SOW, purchase order, invoice, or service agreement."] },
  { heading: "11. Intellectual Property", paragraphs: ["Kashless Ventures and its licensors retain rights in pre-existing software, frameworks, libraries, tools, reusable components, methodologies, documentation, templates, know-how, trademarks, and proprietary materials. Client-specific deliverables are governed by the applicable written agreement."] },
  { heading: "12. Data Protection & Security", paragraphs: ["Each party will handle data in accordance with applicable law and the applicable agreement. Kashless Ventures may implement reasonable technical and organizational safeguards appropriate to the agreed Services."] },
  { heading: "13. Confidentiality", paragraphs: ["Each party will protect confidential information received from the other and use it only for the applicable business relationship, subject to customary exclusions and legal requirements."] },
  { heading: "14. Service Availability & Support", paragraphs: ["Uninterrupted or error-free operation is not guaranteed unless a specific service level or uptime commitment is expressly agreed in writing."] },
  { heading: "15. Limitation of Liability", paragraphs: ["To the maximum extent permitted by applicable law and subject to any different written agreement, Kashless Ventures will not be liable for indirect, incidental, special, consequential, punitive, or loss-of-profit damages. Specific liability caps and remedies are governed by the applicable commercial agreement."] },
  { heading: "16. Indemnity", paragraphs: ["To the extent permitted by law and the applicable agreement, the client agrees to indemnify Kashless Ventures from third-party claims arising from unlawful use of the Services, violation of these Terms, infringement caused by client-provided materials, or breach of contractual or legal obligations."] },
  { heading: "17. Suspension & Termination", paragraphs: ["Kashless Ventures may suspend access to address security risks, unlawful use, material breach, non-payment, or legal requirements, subject to the applicable agreement. Either party may terminate Services in accordance with the applicable written contract."] },
  { heading: "18. Force Majeure", paragraphs: ["Kashless Ventures will not be liable for delay or failure caused by events beyond its reasonable control, including natural disasters, war, government action, widespread network or cloud outages, or failures of third-party infrastructure."] },
  { heading: "19. Governing Law & Dispute Resolution", paragraphs: ["These Terms are governed by the laws of India. Disputes should first be addressed through good-faith discussions. A separate written agreement's dispute-resolution mechanism or jurisdiction applies where specified."] },
  { heading: "20. Modifications", paragraphs: ["Kashless Ventures may update these Terms to reflect changes in Services, technology, business practices, or applicable legal requirements."] },
  { heading: "21. Contact Information", paragraphs: ["Kashless Ventures Private Limited", "Customer Support: Team Kashless", "Department: Support", "Email: info@kashless.in", "Registered Office: Sector 103, Gurgaon, Haryana - 122006", "Website: www.kashless.in"] },
  { heading: "22. Service-Specific Agreements & Disclaimer", paragraphs: ["Use of the Services is subject to these Terms and any applicable service-specific policies, SOWs, commercial agreements, privacy and data-protection terms, and third-party provider terms. Where a specific written agreement applies, it governs the relevant Services to the extent of any conflict."] },
];

export default function TermsConditions() {
  return <LegalPage title="Terms & Conditions" effectiveDate="25 September 2026" updated="25 September 2026"><PolicySections sections={sections} /></LegalPage>;
}
