import LegalPage, { PolicySections } from "@/components/LegalPage";
import { createSeoMetadata } from "@/lib/data";

export const metadata = createSeoMetadata("refundPolicy", "/refund-policy");

const sections = [
  { heading: "1. Introduction", paragraphs: ["This Refund Policy sets out the general terms under which refunds, cancellations, reversals, credits, or adjustments may be considered by Kashless Ventures Private Limited.", "Kashless Ventures provides Technology Solutions, Business Consultation, and Strategic Partnerships, including technology products and services, consulting, implementation, licensing, hardware, support, and related commercial engagements.", "Where a quotation, proposal, invoice, purchase order, Statement of Work, Master Services Agreement, subscription terms, partnership agreement, or other written commercial agreement provides different conditions, those terms apply to the relevant engagement."] },
  { heading: "2. Scope", paragraphs: ["This Policy applies to software, web and mobile development, product engineering, APIs, integrations, FinTech and digital-lending technology, AI, automation, cloud, infrastructure, DevOps, Microsoft licensing, hardware, IT infrastructure, business consultation, process improvement, implementation support, and strategic partnership engagements."] },
  { heading: "3. General Refund Principle", paragraphs: ["Refunds are not automatic and depend on the transaction, stage of delivery, applicable agreement, and third-party terms. Amounts relating to services or products already delivered, activated, consumed, customized, developed, deployed, procured, allocated, or committed may be non-refundable, except where required by law or expressly agreed in writing."] },
  { heading: "4. Service and Product Categories", paragraphs: ["For technology projects, implementation, integration, customization, technical support, consultation, and partnership services, advance, milestone, and resource-related payments may become non-refundable once work, resource allocation, procurement, or implementation begins. Any settlement on cancellation generally considers work completed, deliverables, resources committed, third-party costs, and the applicable agreement.", "Subscriptions may be cancelled before renewal subject to their terms. Activated, assigned, consumed, or committed Microsoft licenses and subscriptions may be non-refundable. Hardware orders may be cancelled before dispatch or procurement commitment where commercially possible and subject to supplier terms; after dispatch, delivery, installation, activation, or configuration, supplier and warranty terms apply."] },
  { heading: "5. Generally Non-Refundable Items", bullets: ["Services already delivered or substantially performed.", "Development, implementation, integration, customization, or consulting work already commenced.", "Third-party software, API, cloud, hosting, licensing, or subscription costs already incurred or committed.", "Activated or consumed licenses and subscriptions.", "Hardware specifically procured, dispatched, delivered, installed, or configured for a client.", "Non-reversible government, statutory, banking, payment-processing, or third-party charges."] },
  { heading: "6. Refund Request Process", paragraphs: ["Refund, cancellation, or billing-correction requests should be submitted through the designated Kashless Ventures support or grievance channel. Include the invoice, order, or transaction ID; payment amount and date; product or service concerned; reason for the request; and relevant supporting documents or correspondence. Kashless Ventures may request information reasonably required to verify the request."] },
  { heading: "7. Verification and Processing", paragraphs: ["Kashless Ventures may verify the payment, transaction, service status, delivery stage, applicable agreement, and relevant third-party conditions before determining whether a refund applies. Requests will normally be acknowledged within 7 working days. Where approved, refunds will generally be initiated within 7-10 business days after approval, subject to bank, payment, manufacturer, licensing partner, supplier, or other third-party processing timelines."] },
  { heading: "8. Exceptions and Chargebacks", paragraphs: ["Refunds may be affected by suspected fraud or misuse, existing chargebacks or payment disputes, regulatory or third-party restrictions, missing verification information, supplier or licensing restrictions, or events beyond reasonable control. Customers should avoid duplicate recovery claims for the same transaction."] },
  { heading: "9. Cancellation and Termination", paragraphs: ["Cancellation and termination are governed by the applicable agreement. Fees for delivered services, completed work, committed resources, third-party obligations, or accrued costs remain payable unless expressly waived in writing. Kashless Ventures may provide a service credit, correction, replacement, adjustment, or other commercially appropriate remedy instead of a monetary refund where appropriate."] },
  { heading: "10. Contact Information", paragraphs: ["Kashless Ventures Private Limited", "Customer Support: Team Kashless", "Department: Support", "Email: info@kashless.in", "Registered Office: Sector 103, Gurgaon, Haryana - 122006", "Website: www.kashless.in"] },
  { heading: "11. Policy Updates", paragraphs: ["Kashless Ventures may update this Refund Policy to reflect changes in its services, products, business processes, supplier arrangements, or applicable legal and regulatory requirements."] },
  { heading: "12. Important Note", paragraphs: ["This Policy is a general framework. Specific refund, cancellation, warranty, replacement, subscription, licensing, milestone, project, consultation, or partnership terms in an applicable quotation, proposal, invoice, SOW, purchase order, MSA, subscription terms, partnership agreement, licensing terms, manufacturer warranty, or other written commercial agreement govern to the extent of any inconsistency."] },
];

export default function RefundPolicy() {
  return <LegalPage title="Refund Policy" effectiveDate="25 September 2026" updated="25 September 2026"><PolicySections sections={sections} /></LegalPage>;
}
